// ============================================================================
// Fixed taxonomies. These mirror the seeded taxonomy_roles / taxonomy_skills
// tables and are used client-side to power the profile intake comboboxes
// (avoids a round-trip and guarantees the options are always available).
// Keep in sync with supabase/migrations/0002_seed_taxonomy.sql.
// ============================================================================

export const ROLES: string[] = [
  "Frontend Developer",
  "Backend Developer",
  "Full-Stack Developer",
  "Mobile Developer (iOS)",
  "Mobile Developer (Android)",
  "DevOps Engineer",
  "Site Reliability Engineer",
  "Data Engineer",
  "Data Scientist",
  "Data Analyst",
  "Machine Learning Engineer",
  "AI Engineer",
  "QA Engineer",
  "Security Engineer",
  "Product Manager",
  "Product Designer",
  "UX Designer",
  "UI Designer",
  "Graphic Designer",
  "Technical Writer",
  "Developer Advocate",
  "Engineering Manager",
  "Solutions Architect",
  "Cloud Engineer",
  "Database Administrator",
  "Blockchain Developer",
  "Game Developer",
  "Embedded Systems Engineer",
  "Customer Support Specialist",
  "Customer Success Manager",
  "Sales Development Rep",
  "Account Executive",
  "Marketing Manager",
  "Content Marketer",
  "SEO Specialist",
  "Social Media Manager",
  "Growth Marketer",
  "Community Manager",
  "Email Marketer",
  "Copywriter",
  "Content Writer",
  "Editor",
  "Project Manager",
  "Program Manager",
  "Operations Manager",
  "Business Analyst",
  "Recruiter",
  "HR Manager",
  "People Ops",
  "Executive Assistant",
  "Virtual Assistant",
  "Bookkeeper",
  "Accountant",
  "Financial Analyst",
  "Legal Counsel",
  "Paralegal",
  "Illustrator",
  "Video Editor",
  "Animator",
  "Sound Designer",
];

export const SKILLS: string[] = [
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "Go",
  "Rust",
  "Ruby",
  "PHP",
  "C++",
  "C#",
  "Swift",
  "Kotlin",
  "React",
  "Next.js",
  "Vue",
  "Angular",
  "Svelte",
  "Node.js",
  "Express",
  "Django",
  "Flask",
  "Ruby on Rails",
  "Spring Boot",
  ".NET",
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Redis",
  "Supabase",
  "Firebase",
  "GraphQL",
  "REST APIs",
  "AWS",
  "GCP",
  "Azure",
  "Docker",
  "Kubernetes",
  "Terraform",
  "CI/CD",
  "Git",
  "Figma",
  "Sketch",
  "Adobe XD",
  "Photoshop",
  "Illustrator",
  "After Effects",
  "Machine Learning",
  "Deep Learning",
  "NLP",
  "Computer Vision",
  "PyTorch",
  "TensorFlow",
  "LangChain",
  "Prompt Engineering",
  "LLMs",
  "SEO",
  "Google Analytics",
  "HubSpot",
  "Salesforce",
  "Mailchimp",
  "Content Strategy",
  "Agile/Scrum",
  "Jira",
  "Notion",
  "Slack",
  "Excel/Sheets",
  "SQL",
  "Data Visualization",
  "Tableau",
  "Communication",
  "Project Management",
  "Team Leadership",
  "Public Speaking",
];

export const EXPERIENCE_LEVELS = [
  { value: "junior", label: "Junior (0-2 yrs)" },
  { value: "mid", label: "Mid (2-5 yrs)" },
  { value: "senior", label: "Senior (5+ yrs)" },
] as const;
