-- ============================================================================
-- Roleflux — taxonomy seed data
-- Fixed vocabularies that constrain profile intake to consistent values.
-- Idempotent: safe to re-run.
-- ============================================================================

insert into public.taxonomy_roles (name, category) values
  ('Frontend Developer', 'Engineering'),
  ('Backend Developer', 'Engineering'),
  ('Full-Stack Developer', 'Engineering'),
  ('Mobile Developer (iOS)', 'Engineering'),
  ('Mobile Developer (Android)', 'Engineering'),
  ('DevOps Engineer', 'Engineering'),
  ('Site Reliability Engineer', 'Engineering'),
  ('Data Engineer', 'Data'),
  ('Data Scientist', 'Data'),
  ('Data Analyst', 'Data'),
  ('Machine Learning Engineer', 'Data'),
  ('AI Engineer', 'Data'),
  ('QA Engineer', 'Engineering'),
  ('Security Engineer', 'Engineering'),
  ('Product Manager', 'Product'),
  ('Product Designer', 'Design'),
  ('UX Designer', 'Design'),
  ('UI Designer', 'Design'),
  ('Graphic Designer', 'Design'),
  ('Technical Writer', 'Content'),
  ('Developer Advocate', 'Engineering'),
  ('Engineering Manager', 'Engineering'),
  ('Solutions Architect', 'Engineering'),
  ('Cloud Engineer', 'Engineering'),
  ('Database Administrator', 'Engineering'),
  ('Blockchain Developer', 'Engineering'),
  ('Game Developer', 'Engineering'),
  ('Embedded Systems Engineer', 'Engineering'),
  ('Customer Support Specialist', 'Support'),
  ('Customer Success Manager', 'Support'),
  ('Sales Development Rep', 'Sales'),
  ('Account Executive', 'Sales'),
  ('Marketing Manager', 'Marketing'),
  ('Content Marketer', 'Marketing'),
  ('SEO Specialist', 'Marketing'),
  ('Social Media Manager', 'Marketing'),
  ('Growth Marketer', 'Marketing'),
  ('Community Manager', 'Marketing'),
  ('Email Marketer', 'Marketing'),
  ('Copywriter', 'Content'),
  ('Content Writer', 'Content'),
  ('Editor', 'Content'),
  ('Project Manager', 'Operations'),
  ('Program Manager', 'Operations'),
  ('Operations Manager', 'Operations'),
  ('Business Analyst', 'Operations'),
  ('Recruiter', 'People'),
  ('HR Manager', 'People'),
  ('People Ops', 'People'),
  ('Executive Assistant', 'Operations'),
  ('Virtual Assistant', 'Operations'),
  ('Bookkeeper', 'Finance'),
  ('Accountant', 'Finance'),
  ('Financial Analyst', 'Finance'),
  ('Legal Counsel', 'Legal'),
  ('Paralegal', 'Legal'),
  ('Illustrator', 'Creative'),
  ('Video Editor', 'Creative'),
  ('Animator', 'Creative'),
  ('Sound Designer', 'Creative')
on conflict (name) do nothing;

insert into public.taxonomy_skills (name, category) values
  ('JavaScript', 'Language'),
  ('TypeScript', 'Language'),
  ('Python', 'Language'),
  ('Java', 'Language'),
  ('Go', 'Language'),
  ('Rust', 'Language'),
  ('Ruby', 'Language'),
  ('PHP', 'Language'),
  ('C++', 'Language'),
  ('C#', 'Language'),
  ('Swift', 'Language'),
  ('Kotlin', 'Language'),
  ('React', 'Frontend'),
  ('Next.js', 'Frontend'),
  ('Vue', 'Frontend'),
  ('Angular', 'Frontend'),
  ('Svelte', 'Frontend'),
  ('Node.js', 'Backend'),
  ('Express', 'Backend'),
  ('Django', 'Backend'),
  ('Flask', 'Backend'),
  ('Ruby on Rails', 'Backend'),
  ('Spring Boot', 'Backend'),
  ('.NET', 'Backend'),
  ('PostgreSQL', 'Database'),
  ('MySQL', 'Database'),
  ('MongoDB', 'Database'),
  ('Redis', 'Database'),
  ('Supabase', 'Database'),
  ('Firebase', 'Database'),
  ('GraphQL', 'Backend'),
  ('REST APIs', 'Backend'),
  ('AWS', 'Cloud'),
  ('GCP', 'Cloud'),
  ('Azure', 'Cloud'),
  ('Docker', 'DevOps'),
  ('Kubernetes', 'DevOps'),
  ('Terraform', 'DevOps'),
  ('CI/CD', 'DevOps'),
  ('Git', 'DevOps'),
  ('Figma', 'Design'),
  ('Sketch', 'Design'),
  ('Adobe XD', 'Design'),
  ('Photoshop', 'Design'),
  ('Illustrator', 'Design'),
  ('After Effects', 'Design'),
  ('Machine Learning', 'AI/ML'),
  ('Deep Learning', 'AI/ML'),
  ('NLP', 'AI/ML'),
  ('Computer Vision', 'AI/ML'),
  ('PyTorch', 'AI/ML'),
  ('TensorFlow', 'AI/ML'),
  ('LangChain', 'AI/ML'),
  ('Prompt Engineering', 'AI/ML'),
  ('LLMs', 'AI/ML'),
  ('SEO', 'Marketing'),
  ('Google Analytics', 'Marketing'),
  ('HubSpot', 'Marketing'),
  ('Salesforce', 'Marketing'),
  ('Mailchimp', 'Marketing'),
  ('Content Strategy', 'Marketing'),
  ('Agile/Scrum', 'Process'),
  ('Jira', 'Process'),
  ('Notion', 'Process'),
  ('Slack', 'Process'),
  ('Excel/Sheets', 'Data'),
  ('SQL', 'Data'),
  ('Data Visualization', 'Data'),
  ('Tableau', 'Data'),
  ('Communication', 'Soft Skill'),
  ('Project Management', 'Soft Skill'),
  ('Team Leadership', 'Soft Skill'),
  ('Public Speaking', 'Soft Skill')
on conflict (name) do nothing;
